# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-live--609063391233"
    dynamodb_table = "tfstate-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-3"
  }
}
