# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-west-3"

  default_tags {
    tags = {
      project   = "launchplate-react"
      managedby = "terraform"
    }
  }
}

# CloudFront can only be deployed in us-east-1, even though CloudFront is a global service.
provider "aws" {
  alias  = "useast1"
  region = "us-east-1"

  default_tags {
    tags = {
      project   = "launchplate-react"
      managedby = "terraform"
    }
  }
}
